export const SUCCESS = "SUCCESS"
export const FAIL = "FAIL"
export const FORBIDDEN = "YOU DON'T HAVE PERMISSION TO ACCESS THIS FUNCTION"
export const LIST_PARTICIPANT_FORBIDDEN = "YOU DON'T HAVE PERMISSION TO ADD LIST PARTICIPANT TO ACTIVITY"
export const MESS_INTERNAL_SERVER_ERROR = "INTERNAL SERVER ERROR"

export enum FAIL_MESSAGE {
    GETALL = "ERROR WHEN GETTING ALL DATA",
    GETID = "ERROR WHEN GETTING DATA WITH ID",
    CREATE = "ERROR WHEN CREATING DATA",
    EDIT = "ERROR WHEN EDITING DATA",
    DELETE = "ERROR WHEN DELETING DATA",
    CATCH_DATA = "ERROR WHEN CATCHING DATA WITH ID",
    UNIDENTIFY = "UNIDENTIFY ID: ",
    PARTICIPANT = "ERROR WHEN GETTING PARTICIPANTS",
    LIST_ACTIVITY_IN_GROUP_UNIONDEPT = "ERROR WHEN GETTING LIST ACTIVITY IN GROUP UNONDEPT",
    LIST_ACTIVITY_IN_GROUP_PARTICIPANT = "ERROR WHEN GETTING LIST ACTIVITY IN GROUP PARTICIPANT"
}

export enum ERROR_DB {
    CATEGORY_NOTFOUND = "CATEGORY ID NOT FOUND: ",
    UNIQUE_CONSTRAINT = "DATABASE UNIQUE CONSTRAINT VIOLANTION",
    ACTIVITY_NOTFOUND = "ACTIVITY ID NOT FOUND: ",
    UNIONDEPT_NOTFOUND = "UNIONDEPT ID NOT FOUND: ",
    USER_NOTFOUND = "USER ID NOT FOUND: ",
    PARTICIPANT_NOTFOUND = "PARTICIPANT ID NOT FOUND: "
}


